apiVersion: v1
kind: ConfigMap
metadata:
  namespace: production
  name: beta-service-config
  labels:
    app: beta-service
data:
  HTTP_HOST: 0.0.0.0
  HTTP_PORT: 8000
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_NAME: votes
  POSTGRES_SSLMODE: false
  GAMMA_SERVICE_URL: http://service-gamma
  DIGEST_SERVICE_URL: http://service-digest
